server:
  port: 8081
spring:
  application:
    name: springboot-demo-user-service
#  profiles:
#    active: local  # 指定使用application-local.yml文件启动spring
  datasource:
    url: jdbc:mysql://localhost:3306/test1105?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: chen1234
    type: com.alibaba.druid.pool.DruidDataSource

#  datasource:
#    driver-class-name: oracle.jdbc.driver.OracleDriver
#    url: jdbc:oracle:thin:@//localhost:1521/demo01
#    username: root
#    password: 123456
#    druid:
#      initial-size: 10
#      max-active: 50
#      max-wait: 30000
#      min-idle: 10

mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml #mapper.xml文件的地址
  type-aliases-package: com.yitong.domain.entity  #这里是配置自动扫描实体类，这样mapper.xml中的参数类型就可以直接写类名
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启控制台打印sql语句
#    map-underscore-to-camel-case: true #将带有下划线的表字段映射为驼峰格式的实体类属性
#    call-setters-on-nulls: true #查询字段为null也返回此字段

eureka:
  client:
    fetch-registry: true #是否检索服务
    register-with-eureka: true
    service-url:
      defaultZone: http://127.0.0.1:8082/eureka/
  instance:
    prefer-ip-address: true #在eureka中显示ip地址
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
#    lease-renewal-interval-in-seconds: 30 #client发送心跳的频率
#    lease-expiration-duration-in-seconds: 60 #表示eureka server从上一次收到client的心跳，等待下一次心跳的超时时间

